from __future__ import annotations

from typing import Protocol

from mt5_risk_bot.models import Account, Bar, OrderResult, Position, SymbolSpec, Tick


class Broker(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def account(self) -> Account: ...
    def symbol(self, name: str) -> SymbolSpec: ...
    def tick(self, name: str) -> Tick: ...
    def rates(self, name: str, timeframe: int, count: int) -> list[Bar]: ...
    def positions(self, magic: int | None = None) -> list[Position]: ...
    def order_check(self, request: dict) -> OrderResult: ...
    def order_send(self, request: dict) -> OrderResult: ...
    def select_symbol(self, name: str) -> bool: ...
